version: "3"

services:
  cataricastori-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - cataricastori
      - cloudflared
  
  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-app}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
    volumes:
      - ./tmp/mariadb:/var/lib/mysql
    networks:
      - cataricastori
  
  adminer:
    image: adminer
    restart: unless-stopped
    environment:
        ADMINER_DESIGN: mvt
        ADMINER_DEFAULT_SERVER: db
    networks:
      - cataricastori

networks:
  cloudflared:
    external: true
  cataricastori:
    driver: bridge